#!/bin/bash
cd `dirname $0` && cd ..

docker-compose exec site /bin/bash -c "\
    bash make_style.sh && \
    python3 manage.py collectstatic --noinput && \
    rm resources/style.css resources/content-description.css resources/ranks.css resources/table.css resources/martor-description.css && \
    rm -r sass_processed && \
    python3 manage.py compilemessages && \
    python3 manage.py compilejsi18n && \
    cp -r resources/ /assets/ && \
    cp 502.html /assets/ && \
    cp logo.png /assets/ && \
    cp robots.txt /assets/"
