server {
    listen 80;
    server_name mokla.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    server_name mokla.org; # or localhost

    ssl_certificate /etc/letsencrypt/live/mokla.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mokla.org/privkey.pem;

    # Standard SSL settings (managed by Certbot)
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    
    client_max_body_size 48M;

    add_header X-UA-Compatible "IE=Edge,chrome=1";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    root /var/www/mokla-site; # Path to your folder
    index mokla.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name code.mokla.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen       443 ssl;
    #listen       [::]:80;
    server_name  code.mokla.org;

    ssl_certificate /etc/letsencrypt/live/code.mokla.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/code.mokla.org/privkey.pem;

    # Standard SSL settings (managed by Certbot)
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    
    client_max_body_size 48M;

    add_header X-UA-Compatible "IE=Edge,chrome=1";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    charset utf-8;
    try_files $uri @icons;
    error_page 502 504 /502.html;

    location ~ ^/502\.html$|^/logo\.png$|^/robots\.txt$ {
        root /assets/;
    }

    location @icons {
        root /assets/resources/icons/;
        log_not_found off;
        error_page 403 = @uwsgi;
        error_page 404 = @uwsgi;
    }

    location @uwsgi {
        uwsgi_read_timeout 600;
        uwsgi_pass site:8000;
        include uwsgi_params;
        uwsgi_param SERVER_SOFTWARE nginx/$nginx_version;
    }

    location /static {
        gzip_static on;
        expires max;
        root /assets/;
    }

    location /media {
        alias /media/;
    }

    location /pdfcache {
        internal;
        root /;
    }

    location /datacache {
        internal;
        root /;
    }

    location /mathoid {
        default_type image/svg+xml;
        alias /cache/mathoid;
    }

    location /texoid {
        default_type image/svg+xml;
        alias /cache/texoid;
    }

    location /event/ {
        proxy_pass http://wsevent:15100/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }

    location /channels/ {
        proxy_read_timeout 120;
        proxy_pass http://wsevent:15102/;
    }
}
